data:
  root_data_path: /home/vadbeg/Data_SSD/Kaggle/cell_instance_segmentation/sartorius-cell-instance-segmentation
  all_annotations_path: /home/vadbeg/Data_SSD/Kaggle/cell_instance_segmentation/sartorius-cell-instance-segmentation/annotations_all.json
  train_annotations_path: /home/vadbeg/Data_SSD/Kaggle/cell_instance_segmentation/sartorius-cell-instance-segmentation/annotations_train.json
  val_annotations_path: /home/vadbeg/Data_SSD/Kaggle/cell_instance_segmentation/sartorius-cell-instance-segmentation/annotations_val.json
